"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-10-06 06:09:52.752651
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_note', sa.String(length=256), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_target'), ['target'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=True),
    sa.Column('transaction_id', sa.String(length=32), nullable=True),
    sa.Column('lease_id', sa.String(length=32), nullable=True),
    sa.Column('change_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('required_role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('transaction_id', sa.String(length=32), nullable=True),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_target'), ['target'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_ts'), ['ts'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=True),
    sa.Column('issuer', sa.String(length=128), nullable=False),
    sa.Column('not_after', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates'))
    )
    op.create_table('change_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('impact', sa.JSON(), nullable=False),
    sa.Column('window', sa.String(length=64), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_requests'))
    )
    op.create_table('chaos_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('injections', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chaos_runs'))
    )
    op.create_table('chatops_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('delivery_status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chatops_events'))
    )
    with op.batch_alter_table('chatops_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatops_events_ts'), ['ts'], unique=False)

    op.create_table('config_items',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('actual', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_items'))
    )
    with op.batch_alter_table('config_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_items_device_id'), ['device_id'], unique=False)

    op.create_table('counters',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_counters'))
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('trigger', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('impact', sa.JSON(), nullable=False),
    sa.Column('safety', sa.JSON(), nullable=False),
    sa.Column('confidence_breakdown', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=True),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_target'), ['target'], unique=False)

    op.create_table('drift_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('desired', sa.JSON(), nullable=True),
    sa.Column('actual', sa.JSON(), nullable=True),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('risk', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('remediation_action', sa.String(length=64), nullable=True),
    sa.Column('transaction_id', sa.String(length=32), nullable=True),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('desired_checksum', sa.String(length=64), nullable=False),
    sa.Column('actual_checksum', sa.String(length=64), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('during_maintenance', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drift_events'))
    )
    with op.batch_alter_table('drift_events', schema=None) as batch_op:
        batch_op.create_index('ix_drift_status_device', ['status', 'device_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_target'), ['target'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('firewall_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('lease_id', sa.String(length=32), nullable=True),
    sa.Column('policy_id', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firewall_rules'))
    )
    with op.batch_alter_table('firewall_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firewall_rules_position'), ['position'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('privileged', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.String(length=256), nullable=True),
    sa.Column('root_cause_entity', sa.String(length=96), nullable=True),
    sa.Column('root_cause_kind', sa.String(length=32), nullable=True),
    sa.Column('root_cause_confidence', sa.String(length=16), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('affected_users', sa.JSON(), nullable=False),
    sa.Column('affected_devices', sa.JSON(), nullable=False),
    sa.Column('affected_services', sa.JSON(), nullable=False),
    sa.Column('impact', sa.JSON(), nullable=False),
    sa.Column('triage', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('recurring', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('detection_source', sa.String(length=64), nullable=False),
    sa.Column('human_required', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mitigated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index('ix_incidents_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_target'), ['target'], unique=False)

    op.create_table('ip_addresses',
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('assignment', sa.String(length=16), nullable=False),
    sa.Column('dhcp_hostname', sa.String(length=128), nullable=True),
    sa.Column('lease_expires', sa.DateTime(), nullable=True),
    sa.Column('conflict_macs', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('address', name=op.f('pk_ip_addresses'))
    )
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_addresses_device_id'), ['device_id'], unique=False)

    op.create_table('leases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('destination_id', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('firewall_state', sa.String(length=16), nullable=False),
    sa.Column('firewall_rule_id', sa.String(length=64), nullable=True),
    sa.Column('risk_at_grant', sa.Integer(), nullable=False),
    sa.Column('identity_confidence_at_grant', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('end_reason', sa.String(length=256), nullable=True),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leases'))
    )
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.create_index('ix_leases_status_expires', ['status', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_user_id'), ['user_id'], unique=False)

    op.create_table('mac_addresses',
    sa.Column('address', sa.String(length=17), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('known', sa.Boolean(), nullable=False),
    sa.Column('interface_id', sa.String(length=64), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('address', name=op.f('pk_mac_addresses'))
    )
    with op.batch_alter_table('mac_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mac_addresses_device_id'), ['device_id'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('active_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_table('remediation_transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('action_name', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('trigger', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('automation_confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('pre_state', sa.JSON(), nullable=False),
    sa.Column('backup', sa.JSON(), nullable=False),
    sa.Column('post_state', sa.JSON(), nullable=False),
    sa.Column('commands', sa.JSON(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('rollback_available', sa.Boolean(), nullable=False),
    sa.Column('rollback_status', sa.String(length=24), nullable=False),
    sa.Column('human_action', sa.String(length=16), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=True),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('drift_id', sa.String(length=32), nullable=True),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediation_transactions'))
    )
    with op.batch_alter_table('remediation_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_transactions_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_transactions_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index('ix_tx_target_action', ['target', 'action_id', 'status'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('old_score', sa.Integer(), nullable=False),
    sa.Column('new_score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index('ix_risk_events_entity', ['entity_type', 'entity_id', 'ts'], unique=False)

    op.create_table('risk_scores',
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('trust_marks', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('entity_type', 'entity_id', name=op.f('pk_risk_scores'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('state_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_state_snapshots'))
    )
    with op.batch_alter_table('state_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_snapshots_ts'), ['ts'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('console_role', sa.String(length=16), nullable=False),
    sa.Column('ad_dn', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('subnet', sa.String(length=32), nullable=False),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=128), nullable=False),
    sa.Column('dhcp_enabled', sa.Boolean(), nullable=False),
    sa.Column('dhcp_pool_size', sa.Integer(), nullable=False),
    sa.Column('dhcp_in_use', sa.Integer(), nullable=False),
    sa.Column('dhcp_stale', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vlans'))
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('expected_vlan_id', sa.Integer(), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('ad_computer', sa.Boolean(), nullable=False),
    sa.Column('expected_hostname', sa.String(length=128), nullable=True),
    sa.Column('dns_name', sa.String(length=128), nullable=True),
    sa.Column('identity_confidence', sa.Integer(), nullable=False),
    sa.Column('identity_level', sa.String(length=16), nullable=False),
    sa.Column('identity_signals', sa.JSON(), nullable=False),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.Column('quarantine_reason', sa.String(length=256), nullable=True),
    sa.Column('pre_quarantine_vlan_id', sa.Integer(), nullable=True),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('expected_ports', sa.JSON(), nullable=False),
    sa.Column('observed_ports', sa.JSON(), nullable=False),
    sa.Column('sim_faults', sa.JSON(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], name=op.f('fk_devices_vlan_id_vlans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_vlan_id'), ['vlan_id'], unique=False)

    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_events_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_events'))
    )
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_events_incident_id'), ['incident_id'], unique=False)

    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_versions_policy_id_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_versions')),
    sa.UniqueConstraint('policy_id', 'version', name=op.f('uq_policy_versions_policy_id'))
    )
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_versions_policy_id'), ['policy_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('logon_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_active_user', ['active', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_device_id'), ['device_id'], unique=False)

    op.create_table('user_groups',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_user_groups_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_groups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_user_groups'))
    )
    op.create_table('interfaces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('switch_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('speed_mbps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['devices.id'], name=op.f('fk_interfaces_switch_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interfaces'))
    )
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interfaces_device_id'), ['device_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('ports', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('consumers', sa.String(length=16), nullable=False),
    sa.Column('rto_minutes', sa.Integer(), nullable=True),
    sa.Column('rpo_minutes', sa.Integer(), nullable=True),
    sa.Column('health_detail', sa.String(length=256), nullable=False),
    sa.Column('last_change', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_services_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_device_id'), ['device_id'], unique=False)

    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['services.id'], name=op.f('fk_dependencies_source_id_services'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['services.id'], name=op.f('fk_dependencies_target_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependencies')),
    sa.UniqueConstraint('source_id', 'target_id', name=op.f('uq_dependencies_source_id'))
    )
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependencies_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependencies_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependencies_target_id'))
        batch_op.drop_index(batch_op.f('ix_dependencies_source_id'))

    op.drop_table('dependencies')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_device_id'))

    op.drop_table('services')
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interfaces_device_id'))

    op.drop_table('interfaces')
    op.drop_table('user_groups')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_device_id'))
        batch_op.drop_index('ix_sessions_active_user')

    op.drop_table('sessions')
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_versions_policy_id'))

    op.drop_table('policy_versions')
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_events_incident_id'))

    op.drop_table('incident_events')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_vlan_id'))

    op.drop_table('devices')
    op.drop_table('vlans')
    op.drop_table('users')
    with op.batch_alter_table('state_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_snapshots_ts'))

    op.drop_table('state_snapshots')
    op.drop_table('settings')
    op.drop_table('risk_scores')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_events_entity')

    op.drop_table('risk_events')
    op.drop_table('reports')
    with op.batch_alter_table('remediation_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_target_action')
        batch_op.drop_index(batch_op.f('ix_remediation_transactions_incident_id'))
        batch_op.drop_index(batch_op.f('ix_remediation_transactions_correlation_id'))

    op.drop_table('remediation_transactions')
    op.drop_table('policies')
    with op.batch_alter_table('mac_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mac_addresses_device_id'))

    op.drop_table('mac_addresses')
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leases_user_id'))
        batch_op.drop_index('ix_leases_status_expires')

    op.drop_table('leases')
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_addresses_device_id'))

    op.drop_table('ip_addresses')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_target'))
        batch_op.drop_index('ix_incidents_status_created')
        batch_op.drop_index(batch_op.f('ix_incidents_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_incidents_correlation_id'))

    op.drop_table('incidents')
    op.drop_table('groups')
    with op.batch_alter_table('firewall_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firewall_rules_position'))

    op.drop_table('firewall_rules')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_ts'))
        batch_op.drop_index(batch_op.f('ix_events_target'))
        batch_op.drop_index(batch_op.f('ix_events_correlation_id'))

    op.drop_table('events')
    with op.batch_alter_table('drift_events', schema=None) as batch_op:
        batch_op.drop_index('ix_drift_status_device')

    op.drop_table('drift_events')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_target'))

    op.drop_table('decisions')
    op.drop_table('counters')
    with op.batch_alter_table('config_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_items_device_id'))

    op.drop_table('config_items')
    with op.batch_alter_table('chatops_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatops_events_ts'))

    op.drop_table('chatops_events')
    op.drop_table('chaos_runs')
    op.drop_table('change_requests')
    op.drop_table('certificates')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_events_target'))
        batch_op.drop_index(batch_op.f('ix_audit_events_correlation_id'))

    op.drop_table('audit_events')
    op.drop_table('approvals')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_target'))
        batch_op.drop_index(batch_op.f('ix_alerts_name'))
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_fingerprint'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
