"""Event vocabulary and the reconciliation-loop phase each event belongs to."""

from __future__ import annotations

PHASES = [
    "OBSERVE", "NORMALIZE", "CORRELATE", "UNDERSTAND", "COMPARE", "POLICY", "RISK",
    "DECIDE", "PLAN", "EXECUTE", "VERIFY", "AUDIT", "RECONCILE",
]

EVENT_PHASE: dict[str, str] = {
    "USER_LOGIN": "OBSERVE", "USER_LOGOUT": "OBSERVE", "AUTH_FAILURE": "OBSERVE",
    "DEVICE_DISCOVERED": "OBSERVE", "DHCP_ASSIGNMENT": "OBSERVE", "ARP_CHANGE": "OBSERVE",
    "DNS_CHANGE": "OBSERVE", "PORT_ACTIVITY": "OBSERVE", "CONFIG_CHANGED": "OBSERVE",
    "FIREWALL_CHANGE": "OBSERVE", "SERVICE_DOWN": "OBSERVE", "SERVICE_RECOVERED": "OBSERVE",
    "ALERT_RECEIVED": "OBSERVE", "FAILURE_INJECTED": "OBSERVE", "ALERT_STALE": "NORMALIZE",
    "ALERT_RESOLVED": "NORMALIZE", "IDENTITY_CONFIDENCE_CHANGED": "UNDERSTAND", "DHCP_CONFLICT": "UNDERSTAND",
    "IDENTITY_MISMATCH": "UNDERSTAND", "UNEXPECTED_SERVICE": "UNDERSTAND",
    "INCIDENT_CREATED": "CORRELATE", "SYMPTOM_CORRELATED": "CORRELATE", "ROOT_CAUSE_IDENTIFIED": "CORRELATE",
    "RECURRING_FAILURE": "CORRELATE", "DRIFT_DETECTED": "COMPARE", "POLICY_CHANGED": "POLICY",
    "POLICY_CONFLICT": "POLICY", "ACCESS_EVALUATED": "POLICY", "RISK_CHANGED": "RISK",
    "DECISION_MADE": "DECIDE", "APPROVAL_REQUESTED": "DECIDE", "APPROVAL_GRANTED": "DECIDE",
    "APPROVAL_REJECTED": "DECIDE", "REMEDIATION_PLANNED": "PLAN", "LEASE_CREATED": "EXECUTE",
    "REMEDIATION_STARTED": "EXECUTE", "FIREWALL_UPDATED": "EXECUTE", "QUARANTINE_STARTED": "EXECUTE",
    "QUARANTINE_RELEASED": "EXECUTE", "LEASE_REVOKED": "EXECUTE", "LEASE_EXPIRED": "RECONCILE",
    "ROLLBACK_STARTED": "EXECUTE", "VERIFICATION_PASSED": "VERIFY", "VERIFICATION_FAILED": "VERIFY",
    "ROLLBACK_COMPLETED": "VERIFY", "ROLLBACK_FAILED": "VERIFY", "REMEDIATION_COMPLETED": "VERIFY",
    "REMEDIATION_FAILED": "VERIFY", "DRIFT_REMEDIATED": "VERIFY", "INCIDENT_MITIGATED": "VERIFY",
    "INCIDENT_RESOLVED": "AUDIT", "CHATOPS_SENT": "AUDIT", "SNAPSHOT_CREATED": "AUDIT",
    "FIREWALL_RECONCILIATION": "RECONCILE", "RECONCILIATION_COMPLETED": "RECONCILE",
    "SYSTEM_MODE_CHANGED": "UNDERSTAND", "MAINTENANCE_STARTED": "POLICY", "MAINTENANCE_ENDED": "RECONCILE",
    "SETTING_CHANGED": "POLICY", "DEMO_SCENE": "OBSERVE", "INCIDENT_UPDATED": "CORRELATE",
}

SEVERITIES = ["debug", "info", "notice", "warning", "high", "critical"]


def phase_for(event_type: str) -> str:
    return EVENT_PHASE.get(event_type, "OBSERVE")
