"""Synthetic history, produced by running the real engines on a time-shifted clock.

Every past incident, transaction, audit record, ChatOps message, risk change and snapshot in a
fresh database was generated by the same code paths the live system uses - not hand-written rows.
"""

from __future__ import annotations

from datetime import timedelta
from typing import TYPE_CHECKING

from sqlalchemy import select

from nexus.models import ChaosRun, Device, Lease, User

if TYPE_CHECKING:
    from nexus.core.context import Context


def process(ctx: Context, label: str | None = None, rounds: int = 2, paced: bool = False) -> None:
    """One synchronous control-loop pass: detect, reconcile, run planned transactions, re-detect."""
    from nexus.core.modes import evaluate_mode
    from nexus.drift.engine import scan as drift_scan
    from nexus.leases.engine import apply_pending, expire_leases
    from nexus.monitoring.detector import scan as detect
    from nexus.remediation.runner import drain_sync
    from nexus.risk.engine import recompute_all
    from nexus.timemachine.snapshots import create_snapshot

    for _ in range(rounds):
        if paced:  # the live loop scans every detection_interval; model that delay in synthetic history
            ctx.clock.shift(timedelta(seconds=ctx.settings.detection_interval))
        with ctx.session() as db:
            detect(ctx, db)
        with ctx.session() as db:
            expire_leases(ctx, db)
            apply_pending(ctx, db)
            drift_scan(ctx, db)
            ctx.runtime.pending_reconcile.clear()
        drain_sync(ctx, time_step=ctx.settings.step_delay_ms / 1000 if paced and ctx.settings.step_delay_ms else (0.65 if paced else 0.0))
    with ctx.session() as db:
        detect(ctx, db)
        recompute_all(ctx, db, recover_trust=False)
        evaluate_mode(ctx, db)
        create_snapshot(ctx, db, label or "reconciliation", label=label, force=True)


def _chaos(ctx: Context, scenario: str) -> None:
    from nexus.chaos.scenarios import run_followup, start

    with ctx.session() as db:
        run, sc = start(ctx, db, scenario, actor="history")
        run_id, followups = run.id, list(sc.followups)
    for _delay, fn in followups:
        with ctx.session() as db:
            run_followup(ctx, db, run_id, fn)
    with ctx.session() as db:
        r = db.get(ChaosRun, run_id)
        if r:
            r.requested_by = "synthetic history"


def _lease(ctx: Context, user: str, device: str, dest: str, port: int, minutes: int, approver: str) -> str | None:
    from nexus.core.decision import approve
    from nexus.leases.engine import request_access

    with ctx.session() as db:
        out = request_access(ctx, db, user_id=user, device_id=device, destination=dest, port=port, reason="Planned administration",
                             duration_minutes=minutes, requested_by=user)
        approval_id = out.get("approval_id")
        lease_id = (out.get("lease") or {}).get("id")
    if approval_id:
        with ctx.session() as db:
            approve(ctx, db, approval_id, approver, note="approved (outside business hours, change ticket on file)")
    return lease_id


def paced(ctx: Context, label: str | None = None, rounds: int = 2) -> None:
    process(ctx, label, rounds, paced=True)


def generate(ctx: Context) -> None:
    from nexus.leases.engine import revoke_lease

    real_now = ctx.clock.now()
    at = lambda minutes: ctx.clock.set_time(real_now - timedelta(minutes=minutes))  # noqa: E731
    at(7 * 1440)
    with ctx.session() as db:
        for user, device in (("eldar", "PC-023"), ("aysel", "PC-024"), ("murad", "PC-025")):
            ctx.world.logon(db, user, device)
    paced(ctx, "baseline (7 days ago)")
    at(6 * 1440 - 554)
    _chaos(ctx, "kill-nginx")
    paced(ctx)
    at(5 * 1440 - 130)
    _chaos(ctx, "fail-remediation")
    paced(ctx)
    at(5 * 1440 - 150)
    with ctx.session() as db:
        from nexus.chaos.scenarios import operator_fix

        run_id = db.scalar(select(ChaosRun.id).where(ChaosRun.scenario == "fail-remediation").order_by(ChaosRun.started_at.desc()))
        if run_id:
            operator_fix(ctx, db, run_id, "eldar")
    paced(ctx)
    at(4 * 1440 - 300)
    _chaos(ctx, "add-firewall-rule")
    paced(ctx)
    at(3 * 1440 - 700)
    _chaos(ctx, "kill-nginx")
    paced(ctx)
    at(2 * 1440 - 400)
    _chaos(ctx, "break-ssh-config")
    paced(ctx)
    at(1440 - 200)
    _chaos(ctx, "fill-disk")
    paced(ctx)
    at(840)
    _chaos(ctx, "kill-nginx")
    paced(ctx, "overnight nginx failure")
    at(540)
    _chaos(ctx, "break-monitoring")
    paced(ctx)
    at(180)
    _lease(ctx, "murad", "PC-025", "LINUX01", 22, 30, approver="eldar")
    paced(ctx)
    at(150)
    paced(ctx)
    at(120)
    _lease(ctx, "eldar", "PC-023", "DC01", 3389, 30, approver="murad")
    paced(ctx)
    at(89)
    paced(ctx)
    at(75)
    lease_id = _lease(ctx, "murad", "PC-025", "APP01", 22, 60, approver="eldar")
    paced(ctx)
    at(60)
    if lease_id:
        with ctx.session() as db:
            revoke_lease(ctx, db, lease_id, "work completed", actor="murad")
    paced(ctx)
    at(30)
    with ctx.session() as db:
        ctx.world.set_config(db, "LINUX01", "docker", {"live-restore": False}, actor="deploy-pipeline", reason="docker-ce package upgrade reset daemon.json")
    paced(ctx)
    at(25)
    with ctx.session() as db:
        ctx.world.set_config(db, "MON01", "motd", {"banner": "Welcome to MON01"}, actor="admin@MON01", reason="edited /etc/motd")
    paced(ctx)
    at(20)
    _lease(ctx, "murad", "PC-025", "APP01", 22, 120, approver="eldar")
    paced(ctx)
    at(10)
    _lease(ctx, "eldar", "PC-023", "LINUX01", 22, 30, approver="murad")
    paced(ctx)
    ctx.clock.reset()
    paced(ctx, "startup", rounds=1)
    ctx.clock.reset()
    with ctx.session() as db:
        for dev in db.scalars(select(Device)):
            dev.last_seen = ctx.clock.now()
        _ = db.scalars(select(Lease)).all(), db.scalars(select(User)).all()

