flowchart TB
  NET((Internet)) --- PF[PFSENSE 10.10.10.1<br/>firewall, routing, DHCP]
  PF ---|trunk Gi1/0/1| SW[SW-CORE01 10.10.10.2]
  SW --- V10[VLAN 10 MANAGEMENT<br/>10.10.10.0/24]
  SW --- V20[VLAN 20 SERVERS<br/>10.20.20.0/24]
  SW --- V30[VLAN 30 USERS<br/>10.30.30.0/24]
  SW --- V40[VLAN 40 MONITORING<br/>10.40.40.0/24]
  SW --- V50[VLAN 50 DMZ<br/>10.50.50.0/24]
  SW --- V99[VLAN 99 QUARANTINE<br/>10.99.99.0/24]
  V20 --- DC01[DC01 AD DS, DNS, NTP]
  V20 --- L1[LINUX01 Nginx, SSH, Docker]
  V20 --- A1[APP01 portal, PostgreSQL]
  V40 --- M1[MON01 Prometheus, Grafana, Loki]
  V30 --- P23[PC-023 Eldar]
  V30 --- P24[PC-024 Aysel]
  V30 --- P25[PC-025 Murad]
