"""Markdown/HTML report generation: incident reports, run reports (demo/blackout), stored as Report rows."""

from __future__ import annotations

import html
import re
from datetime import datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from nexus.ids import new_id
from nexus.models import (
    Alert,
    AuditEvent,
    ChatOpsEvent,
    Decision,
    DriftEvent,
    Incident,
    IncidentEvent,
    RemediationTransaction,
    Report,
    RiskEvent,
)

if TYPE_CHECKING:
    from nexus.core.context import Context


def _t(ctx: Context, dt: datetime | None, fmt: str = "%H:%M:%S") -> str:
    return dt.astimezone(ctx.clock.site_tz).strftime(fmt) if dt else "-"


def incident_markdown(ctx: Context, db: Session, inc: Incident) -> str:
    alerts = db.scalars(select(Alert).where(Alert.incident_id == inc.id).order_by(Alert.first_seen)).all()
    events = db.scalars(select(IncidentEvent).where(IncidentEvent.incident_id == inc.id).order_by(IncidentEvent.ts, IncidentEvent.id)).all()
    txs = db.scalars(select(RemediationTransaction).where(RemediationTransaction.incident_id == inc.id).order_by(RemediationTransaction.created_at)).all()
    decisions = db.scalars(select(Decision).where(Decision.incident_id == inc.id).order_by(Decision.ts)).all()
    drift = db.scalars(select(DriftEvent).where(DriftEvent.incident_id == inc.id)).all()
    chat = db.scalars(select(ChatOpsEvent).where(ChatOpsEvent.correlation_id == inc.correlation_id).order_by(ChatOpsEvent.ts)).all()
    risk = db.scalars(select(RiskEvent).where(RiskEvent.entity_id == inc.target, RiskEvent.ts >= inc.created_at).order_by(RiskEvent.ts).limit(12)).all()
    counts = (inc.impact or {}).get("counts", {})
    L = [f"# {inc.id} - {inc.title}", "",
         f"> Generated by NEXUS OMNIS {ctx.clock.now().astimezone(ctx.clock.site_tz):%Y-%m-%d %H:%M} ({ctx.clock.site_tz}). Environment: **{ctx.environment_label}**.", "",
         "## Summary", "", inc.summary or inc.title, "",
         "| Field | Value |", "|---|---|",
         f"| Severity | {inc.severity} |", f"| Priority | {inc.priority} |", f"| Status | {inc.status} |", f"| Category | {inc.category} |",
         f"| Detected | {_t(ctx, inc.created_at, '%Y-%m-%d %H:%M:%S')} via {inc.detection_source} |",
         f"| Resolved | {_t(ctx, inc.resolved_at, '%Y-%m-%d %H:%M:%S')} |", f"| Correlation ID | `{inc.correlation_id}` |",
         f"| Human action | {'REQUIRED' if inc.human_required else 'NOT REQUIRED'} |", "",
         "## Affected assets and users", "",
         f"- Devices ({counts.get('devices', len(inc.affected_devices or []))}): {', '.join(inc.affected_devices or []) or 'none'}",
         f"- Services ({counts.get('services', len(inc.affected_services or []))}): {', '.join(inc.affected_services or []) or 'none'}",
         f"- Users ({counts.get('users', len(inc.affected_users or []))}): {', '.join(inc.affected_users or []) or 'none'}", "",
         "## Timeline", "", "| Time | Stage | Event |", "|---|---|---|"]
    L += [f"| {_t(ctx, e.ts)} | {e.stage} | {e.message.replace('|', '/')} |" for e in events]
    L += ["", "## Root cause", "", f"**{inc.root_cause or 'not determined'}** (confidence {inc.root_cause_confidence or '-'}, deterministic analysis)", "",
          "### Evidence", ""] + [f"- {e}" for e in (inc.evidence or ["none recorded"])]
    L += ["", "### Alerts", ""] + [f"- `{a.id}` {a.name} on {a.target} ({a.source}, {a.status}, first seen {_t(ctx, a.first_seen)})" for a in alerts]
    L += ["", "## Risk evolution", ""] + ([f"- {_t(ctx, r.ts)} {r.entity_id}: {r.old_score} -> {r.new_score} ({r.reason})" for r in risk] or ["- no risk change recorded"])
    L += ["", "## Configuration drift", ""] + ([f"- `{d.id}` {d.device_id} {d.component}.{d.key}: desired `{d.desired}` actual `{d.actual}` ({d.classification}, {d.status})" for d in drift] or ["- none linked"])
    L += ["", "## Decisions", ""] + ([f"- `{d.id}` {d.action_id} -> **{d.outcome}** at {d.confidence}% confidence: {'; '.join(d.reasons)}" for d in decisions] or ["- none"])
    L += ["", "## Remediation", ""]
    for tx in txs:
        L += [f"### {tx.id} - {tx.action_name} ({tx.status})", "", "| Step | Status | Detail |", "|---|---|---|"]
        L += [f"| {s['name']} | {s['status']} | {str(s.get('detail', '')).replace('|', '/')[:160]} |" for s in tx.steps]
        L += ["", "Commands:", ""] + [f"- `{c.get('command')}` -> exit {c.get('exit_code')}" for c in (tx.commands or []) if isinstance(c, dict) and "exit_code" in c]
        L += ["", "Verification:", ""] + [f"- {'PASS' if v['passed'] else 'FAIL'} {v['probe']}: {v['detail']}" for v in (tx.verification or [])]
        L += ["", f"Rollback: {tx.rollback_status}", ""]
    if not txs:
        L += ["No automated remediation was executed.", ""]
    L += ["## ChatOps", ""] + ([f"- {_t(ctx, m.ts)} {m.title} -> {m.provider} ({m.delivery_status})" for m in chat] or ["- none"])
    L += ["", "## Final state", "", f"Incident status **{inc.status}**" + (f", resolved after {int((inc.resolved_at - inc.created_at).total_seconds())} s" if inc.resolved_at else "") + ".", "",
          "## Recommendations", ""] + ([f"- {r}" for r in (inc.recommendations or [])] or ["- No follow-up required beyond normal review."])
    if inc.recurring:
        L += ["", f"> Recurring failure: {inc.recurring.get('occurrences')} occurrences in {inc.recurring.get('period_days')} days. {inc.recurring.get('note', '')}"]
    return "\n".join(L) + "\n"


def run_report_markdown(ctx: Context, db: Session, title: str, since: datetime, intro: str) -> str:
    incs = db.scalars(select(Incident).where(Incident.created_at >= since).order_by(Incident.created_at)).all()
    txs = db.scalars(select(RemediationTransaction).where(RemediationTransaction.created_at >= since).order_by(RemediationTransaction.created_at)).all()
    audits = db.scalars(select(AuditEvent).where(AuditEvent.ts >= since).order_by(AuditEvent.ts)).all()
    ok = sum(1 for t in txs if t.result == "SUCCESS")
    L = [f"# {title}", "", f"> {ctx.environment_label}. Generated {ctx.clock.now().astimezone(ctx.clock.site_tz):%Y-%m-%d %H:%M:%S}. Measurements below come from this run.", "",
         intro, "", "## Outcome", "", f"- Incidents: {len(incs)} ({sum(1 for i in incs if i.status in ('RESOLVED', 'MITIGATED'))} resolved or mitigated, "
         f"{sum(1 for i in incs if i.human_required)} needing a human)", f"- Remediation transactions: {len(txs)} ({ok} verified successful, "
         f"{sum(1 for t in txs if t.status == 'ROLLED_BACK')} rolled back, {sum(1 for t in txs if t.status == 'AWAITING_APPROVAL')} awaiting approval)",
         f"- Audit records: {len(audits)}", "", "## Incidents", "", "| ID | Priority | Title | Root cause | Status |", "|---|---|---|---|---|"]
    L += [f"| {i.id} | {i.priority} | {i.title} | {(i.root_cause or '-').replace('|', '/')} | {i.status} |" for i in incs]
    L += ["", "## Actions", "", "| TX | Action | Target | Status | Duration |", "|---|---|---|---|---|"]
    L += [f"| {t.id} | {t.action_name} | {t.target} | {t.status} | {t.duration_ms or '-'} ms |" for t in txs]
    return "\n".join(L) + "\n"


def save_report(ctx: Context, db: Session, kind: str, title: str, markdown: str, subject: str | None = None) -> Report:
    rep = Report(id=new_id(db, "report"), kind=kind, title=title, subject=subject, markdown=markdown, created_at=ctx.clock.now())
    db.add(rep)
    db.flush()
    return rep


def markdown_to_html(md: str, title: str = "NEXUS report") -> str:
    out, in_list, in_table, in_code = [], False, False, False

    def inline(s: str) -> str:
        s = html.escape(s)
        s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
        return re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)

    for line in md.splitlines():
        if line.startswith("```"):
            out.append("</pre>" if in_code else "<pre>")
            in_code = not in_code
            continue
        if in_code:
            out.append(html.escape(line))
            continue
        if in_list and not line.startswith("- "):
            out.append("</ul>")
            in_list = False
        if in_table and not line.startswith("|"):
            out.append("</table>")
            in_table = False
        if line.startswith("|"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if set("".join(cells)) <= set("-: "):
                continue
            if not in_table:
                out.append("<table>")
                in_table = True
                out.append("<tr>" + "".join(f"<th>{inline(c)}</th>" for c in cells) + "</tr>")
            else:
                out.append("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in cells) + "</tr>")
        elif line.startswith("#"):
            level = len(line) - len(line.lstrip("#"))
            out.append(f"<h{level}>{inline(line[level:].strip())}</h{level}>")
        elif line.startswith("- "):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{inline(line[2:])}</li>")
        elif line.startswith("> "):
            out.append(f"<blockquote>{inline(line[2:])}</blockquote>")
        elif line.strip():
            out.append(f"<p>{inline(line)}</p>")
    if in_list:
        out.append("</ul>")
    if in_table:
        out.append("</table>")
    css = ("body{font:15px/1.55 system-ui,sans-serif;max-width:980px;margin:2rem auto;padding:0 1rem;color:#1d2733}table{border-collapse:collapse;"
           "width:100%;margin:1rem 0}td,th{border:1px solid #d5dde6;padding:.35rem .5rem;text-align:left;vertical-align:top}th{background:#eef2f6}"
           "code{background:#eef2f6;padding:0 .25rem;border-radius:3px}blockquote{border-left:3px solid #6d5bd0;margin:1rem 0;padding:.25rem 1rem;color:#4a5866}"
           "h1{font-size:1.6rem}h2{margin-top:2rem;border-bottom:1px solid #d5dde6}")
    return f"<!doctype html><html lang=en><meta charset=utf-8><title>{html.escape(title)}</title><style>{css}</style><body>{''.join(out)}</body></html>"


def report_dict(r: Report) -> dict[str, Any]:
    return {"id": r.id, "kind": r.kind, "title": r.title, "subject": r.subject, "created_at": r.created_at.isoformat(), "markdown": r.markdown}
